spring.application.name=java-messaging
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=codingnfun2025@gmail.com
spring.mail.password=duke awpg hdqm hltg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true